version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn

      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: Install dependencies
          command: yarn

      - run:
          name: Flow
          command: yarn flow:check

      - run:
          name: Eslint
          command: yarn eslint

      - run:
          name: Tests
          command: yarn test --ci --maxWorkers=2

      - run:
          name: Prettier test
          command: yarn prettier:test

  deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build and deploy
          command: yarn deploy:storybook --ci --host-token-env-variable=GITHUB_TOKEN

  deploy-surge:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build storybook
          command: yarn build:storybook
      - run:
          name: Deploy storybook to surge
          command: yarn deploy:surge
      - run:
          name: Update url
          command: yarn deploy:updateURL ${CIRCLE_BRANCH} https://orbit-components-$(git rev-parse --abbrev-ref HEAD | sed -e 's/[^a-zA-Z0-9]/-/g').surge.sh

workflows:
  version: 2
  test_and_deploy_branch:
    jobs:
      - test
      - deploy-surge:
          requires:
            - test
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
              - master
