# name: Tracking update

# on:
#   schedule:
#     # 0 9 1 * *   # runs once in a month at 1st day at 9:00
#     - cron: "0 9 1 * *"

# jobs:
#   track:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Get timestamp
#         uses: gerred/actions/current-time@master
#         id: current-time

#       - name: Node
#         uses: ./.github/actions/node

#       - name: Install SSH Key
#         uses: shimataro/ssh-key-action@v2
#         with:
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           known_hosts: ${{ secrets.SSH_HOST }}

#       - name: Setup git identity
#         uses: fregante/setup-git-user@v1

#       - name: Tracking
#         env:
#           GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
#         run: |
#           yarn tracking build
#           yarn tracking:fetch
#           git add --all
#           git commit -m "chore(tracking): update tracking"

#       - name: Create PR
#         uses: peter-evans/create-pull-request@v3
#         with:
#           base: master
#           branch: chore/update-tracking-data
#           token: ${{ secrets.PAT }}
#           commit-message: New tracking data
#           delete-branch: true
#           title: "chore(tracking): new tracking data"
#           body: |
#             - Automatically generated PR.
#             - Updated tracking data for ${{ steps.current-time.outputs.time }}
#           labels: |
#             tracking
#             Documentation
#           assignees: mainframev
#           reviewers: mainframev
#           draft: false
