name: Documentation updates

on:
  schedule:
    - cron: "0 15 * * *"

jobs:
  doc-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_HOST }}

      - name: Node
        uses: ./.github/actions/node

      - name: Setup git identity
        run: |
          git config --global user.name "Github Actions Bot"
          git config --global user.email "vgenaev@gmail.com"

      - name: Update component statuses
        run: |
          yarn check:statuses
          git add --all
          git diff-index --quiet HEAD || git commit -m "chore: update component statuses"

      - name: Update svgs
        run: |
          yarn components fetch:icons
          git add --all
          git diff-index --quiet HEAD || git commit -m "feat(icons): update icons from figma"
        env:
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}

      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          base: master
          branch: chore/update-icons-and-svgs
          token: ${{ secrets.PAT }}
          delete-branch: true
          title: "docs: documentation updates"
          body: |
            - Automatically generated PR.
            - Check component statuses updates and new svgs in figma
          labels: |
            Icons
            Documentation
          assignees: mainframev
          reviewers: mainframev
          draft: false
